version: '3'
services:

  main:
    container_name: main
    build:
      context: ./main
    volumes:
    - ./data:/data
    - ./input:/usr/src/app/output
    depends_on:
    - neodb
    stdin_open: true
    tty: true

  neodb:
    container_name: neodb
    image: 'neo4j:latest'
    ports:
    - '7474:7474'
    - '7687:7687'
    environment:
    - NEO4J_AUTH=none
    logging:
        driver: none