version: '3'
services:

  main:
    container_name: main
    build:
      context: ./main
    volumes:
    - ./data:/data
    - ./input:/usr/src/app/output
    - ./graphs:/graphs
    depends_on:
    - neodb
    ports:
    - '81:8080'

  front:
      container_name: front_end
      build:
        context: ./front_end/docker
#      depends_on:
#      - main
      ports:
      - '80:80'
      volumes:
      - ./graphs:/usr/share/nginx/html/assets/graphs

  neodb:
    container_name: neodb
    image: 'neo4j:latest'
    ports:
    - '7474:7474'
    - '7687:7687'
    environment:
    - NEO4J_AUTH=none
    logging:
        driver: none